baseURL = "https://datascientistsamchan.github.io/"
languageCode = "en-us"
title = "Sam Chan"
theme = "berbera"

pygmentsCodeFences=true
pygmentsUseClasses=true
canonifyURLs=true
publishDir="docs"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]
